name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Amper
      run: |
        curl -s https://download.jetbrains.com/toolbox/amper/install.sh | bash
        export PATH="$HOME/.amper/bin:$PATH"

    - name: Build project
      run: ./amper build

    - name: Run tests
      run: ./amper test